// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace News.iOS
{
	public partial class ArticleImageView : UIView
	{
		public ArticleImageView (IntPtr handle) : base (handle)
		{
		}
	}
}
