// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Morphous.Native.iOS.UI;
using UIKit;

namespace News.iOS
{
	public partial class ContentItemArticleView : ContentItemView
	{
		public ContentItemArticleView (IntPtr handle) : base (handle)
		{
		}
	}
}
