// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Morphous.Native.iOS.UI;
using UIKit;

namespace Morphous.Native.iOS
{
	public partial class ContentItemImageSummaryView : ContentItemView
	{
		public ContentItemImageSummaryView (IntPtr handle) : base (handle)
		{
		}
	}
}
