// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Morphous.Native.iOS.UI
{
	public partial class DefaultContentItemView : ContentItemView
	{
		public DefaultContentItemView (IntPtr handle) : base (handle)
		{
		}
	}
}
