// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Morphous.Native.iOS.UI;
using UIKit;

namespace MainSample.iOS
{
	public partial class MyContentItem : ContentItemView
	{
		public MyContentItem (IntPtr handle) : base (handle)
		{
		}
	}
}
