// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Morphous.Native.Models;
using UIKit;

namespace Morphous.Native.iOS
{
    public partial class BodyPartView : ElementView<IBodyPart>
	{
		public BodyPartView (IntPtr handle) : base (handle)
		{
		}

        protected override void Bind()
        {
            base.Bind();

            NSError error = null;
            var documentAttributes = new NSAttributedStringDocumentAttributes { DocumentType = NSDocumentType.HTML, StringEncoding = NSStringEncoding.UTF8 };
            var attributedString = new NSAttributedString(Element.Html, documentAttributes, ref error);

            HtmlLabel.AttributedText = attributedString;
        }
	}
}
