// This file has been autogenerated from a class added in the UI designer.

using System;
using FFImageLoading;
using Foundation;
using Morphous.Native.Models;
using UIKit;

namespace Morphous.Native.iOS
{
    public partial class ImagePartView : ElementView<IImagePart>
	{
		public ImagePartView (IntPtr handle) : base (handle)
		{
		}

        protected override void Bind()
        {
            base.Bind();

            ImageService.Instance.LoadUrl($"{Mph.BaseUrl}{Element.Url}")
                .Retry(3, 200)
                .Into(ImageView);
        }
	}
}
