// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Morphous.Native.Models;
using UIKit;

namespace Morphous.Native.iOS
{
    public partial class TermPartView : ElementView<ITermPart>
	{
		public TermPartView (IntPtr handle) : base (handle)
		{
		}

        protected override void Bind()
        {
            base.Bind();
            var test = Element;
        }
	}
}
