// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using Morphous.Native.Models;
using UIKit;

namespace Morphous.Native.iOS.UI.Elements
{
    public partial class TitlePartView : ElementView<ITitlePart>
	{
		public TitlePartView (IntPtr handle) : base (handle)
		{
		}

        protected override void Bind()
        {
            base.Bind();
            TitleLabel.Text = Element.Title;

            if (Element.Zone.ContentItem == DisplayContext.RootContentItem)
            {
                DisplayContext.ViewController.Title = Element.Title;
            }
        }
	}
}
