// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Morphous.Native.iOS.UI.Elements
{
	public partial class TitlePartView : UIView
	{
		public TitlePartView (IntPtr handle) : base (handle)
		{
		}
	}
}
